### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by esamattis** [tftp-go-team/hooktftp#1]
- [x] drop extra privileges on start 
- [ ] go docs
- [x] readme (user docs)
- [ ] blog post
- [x] time out for disconnected clients
- [x] http hook
- [x] path expand escapes for file hook
- [x] hook refactoring
- [x] close readers (files) after sending

**Comment by rmedaer** [comment]
As you can see in my pull request, I already put it in version 1.0.0. But the last 2 points (go docs + blog post) are not completed.
I'm not sure I could do something for your blog although what about go docs ? You meaning code documentation ? Which kind of doc generator did you imagine ?

Cheers,

**Comment by epeli** [comment]
We can skip those. I was planning to write something general about Go, but that ship has sailed for me.

For docs I was planning to use the standard Go documentation tool but I don't think that's really needed for 1.0 because this is not library.
