### ISSUE TITLE
Feature: TFTP write requests

### ISSUE THREAD

**Issue by rmedaer** [tftp-go-team/hooktftp#14]
Hi,
Currently we can only use hooktftp in "read-only". Indeed you can only do GET requests. It could be great to be able to write files such as classic TFTP server by using PUT requests.

We should be able to implement with current 3 hooks (file, shell, http) meaning we have to transpose PUT request depending hook. For example with...
- file hook: Nothing really difficult to imagine; just write file.
- shell hook: Send stream from TFTP request to shell stdin.
- http hook: Convert TFTP PUT request into HTTP POST request and send stream as content of HTTP query.

What's your feeling about it ?

**Comment by epeli** [comment]
I'm all for it but I'm not personally going to implement it myself.
