### ISSUE TITLE
Pluggable logger

### ISSUE THREAD

**Issue by tfheen** [tftp-go-team/hooktftp#16]
Currently, syslog is assumed (via the logger package). I'm using just the tftp library and would prefer to have integration either with the standard logging library (or at least have it compile when just importing tftp).

A trivial workaround for the latter is:

```
diff --git a/src/tftp/parse_rrq.go b/src/tftp/parse_rrq.go
index 1a3a9a6..727955d 100644
--- a/src/tftp/parse_rrq.go
+++ b/src/tftp/parse_rrq.go
@@ -3,9 +3,10 @@ package tftp
 import (
 	"encoding/binary"
 	"fmt"
-	"strconv"
 	"net"
-	"logger"
+	"strconv"
+
+	"github.com/epeli/hooktftp/src/logger"
 )
 
 type Request struct {
diff --git a/src/tftp/rrq_response.go b/src/tftp/rrq_response.go
index 8d8a414..14db8cd 100644
--- a/src/tftp/rrq_response.go
+++ b/src/tftp/rrq_response.go
@@ -7,7 +7,8 @@ import (
 	"net"
 	"strconv"
 	"time"
-	"logger"
+
+	"github.com/epeli/hooktftp/src/logger"
 )
 
 type Connection interface {
```

but I'd be happy with alternative solutions too. Suggestions? Is this something you could be interested in fixing (or pointing me in the direction you want it fixed)?

**Comment by rmedaer** [comment]
I would prefer to remove all references to "logger" from tftp package. And manage logging with exceptions.
Currently, there is only one "non-fatal" log message:
```
tftp/rrq_response.go:100:     logger.Debug("Got previous ACK %d. Retrying...", acknum)
```
I guess is not a very interesting message and it could be remove.

About logger.Err calls, I propose you to remove them from parse_rrq.go and manage them through exception handling.

@tfheen is it ok for you ?

**Comment by epeli** [comment]
Side note: It was my plan all long to make the tftp library importable for other projects too. So +1 from me.

**Comment by tfheen** [comment]
]] Raphaël Medaer 

> About logger.Err calls, I propose you to remove them from parse_rrq.go and manage them through exception handling.
> 
> @tfheen is it ok for you ?

Yes, that would be perfect. :-)  (By exceptions, I assume you mean panics?)

Do you want a pull request for this, or do you want to do it yourself?

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by rmedaer** [comment]
@tfheen I'll do it my self we the advices of @epeli about

**Comment by rmedaer** [comment]
(Sorry for closing/reopening, bad manipulation !)

@tfheen I'll do it my self we the advices of @epeli about packaging.
@epeli, @sspans do we create a new repository dedicated to tftp library or just modifying this one ?

**Comment by epeli** [comment]
Is it technically possible to import the tftp library only from this repository? (I'm no Go expert).

But even if it's possible the library users would have to download all the hooktftp related code too which is not ideal.

If there is demand we can surely create an another repository too. Maybe even an organisation.

**Comment by rmedaer** [comment]
It's basically what's @tfheen do by importing `github.com/epeli/hooktftp/src/tftp` I guess. So yes. But it's maybe easier to maintain a standardized TFTP package library out of this project. I mean @tfheen seems to only need to contribute to this part of the project.

If you are OK with it. I suggest to create an organisation for libgotftp.

**Comment by epeli** [comment]
I'm all in with the organization. I think it would be actually best for the project since I'm not able to contribute to this very actively at the moment.

Can you guys continue if I create the `libgotftp` organization (or `hooktftp`?), add you as co-owners (@rmedaer & @sspans) to it and transfer this repository to it?

**Comment by rmedaer** [comment]
Ok let's create it.
What about organisation name __tftp-go-team__ ? It's more generic than libgotftp organization.
With following repositories: 
  * __libgotftp__: current tftp directory.
  * __hooktftp__: our current main project using libgotftp.

I you are OK, I create it now with following co-owners: @epeli @sspans /me, and you can transfer repository to organization.

 (But you can, as you would prefer create the organization your self ;-) )

**Comment by epeli** [comment]
> I you are OK, I create it now with following co-owners: @epeli @sspans /me, and you can transfer repository to organization.

Ok!

**Comment by epeli** [comment]
Transferred. Take a good care of it! :)

**Comment by rmedaer** [comment]
Thank's. I close this story and open a new one to split tftp directory.
FYI @tfheen it should be done tomorrow.

**Comment by tfheen** [comment]
]] Raphaël Medaer 

> FYI @tfheen it should be done tomorrow.

Thanks for the super-quick movement on this.  Much appreciated.  Let me
know if there's anything I can do to help. :-)

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are
