### ISSUE TITLE
Split tftp package to libgotftp repository

### ISSUE THREAD

**Issue by rmedaer** [tftp-go-team/hooktftp#17]
`tftp`package has to be used by third application. Such as suggested in #16 the goal of this story is to move tftp package into a new dedicated repository.

__Note:__
Don't forget to move unit-tests for this specific package.

FYI: @tfheen

**Comment by rmedaer** [comment]
Done !
  * Created a new repository [libgotftp](https://github.com/tftp-go-team/libgotftp) with TFTP library from hooktftp.
  * In [libgotftp](https://github.com/tftp-go-team/libgotftp):
    * Removed references to `logger`. The logs are now sent in error.
  * In [hooktftp](https://github.com/tftp-go-team/hooktftp):
    * Removed `tftp`package. Replaced local import to [libgotftp](https://github.com/tftp-go-team/libgotftp).
    * Updated Makefile to `go get`deps.

FYI: @tfheen you should be able to import [libgotftp](https://github.com/tftp-go-team/libgotftp) such as [src/hooktftp.go:16](https://github.com/tftp-go-team/hooktftp/blob/master/src/hooktftp.go). Please let me know if it works fine for you ! ;-)

**Comment by tfheen** [comment]
]] Raphaël Medaer 

> FYI: @tfheen you should be able to import libgotftp such as src/hooktftp.go:16. Please let me know if it works fine for you ! ;-)

Seems to work fine.

It'd be even nicer if you could drop the trailing `/src`, but that's not
a big deal for me.

Thanks for fixing this. :-)

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by rmedaer** [comment]
I understand that you would prefer to have sources in root directory (and **not** in `src`). I like to have `src`directory myself. I don't know about contributors feeling. Depending global feeling we can change... or not ! ;-)

Do you know if it's possible to add configuration file in root dir to redirect in `src` ? Maybe a good win-win !

**Comment by tfheen** [comment]
]] Raphaël Medaer 

> I understand that you would prefer to have sources in root directory
> (and not in src). I like to have srcdirectory myself. I don't know
> about contributors feeling. Depending global feeling we can
> change... or not ! ;-)

It's a minor inconvenience, nothing more. :-)

> Do you know if it's possible to add configuration file in root dir to
> redirect in src ? Maybe a good win-win !

I don't know, sorry.  Maybe ask on golang-nuts?

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are
