### ISSUE TITLE
File-descriptor leaks

### ISSUE THREAD

**Issue by sspans** [tftp-go-team/hooktftp#22]
In production I'm hitting a few file-descriptor leaks. I'll investigate soonish.

**Comment by brmzkw** [comment]
By closing the connection in res.End(), there's no leak when the transfer is successful.

We should consider to move the call to `res.End()` in a defer, so the connection will always be closed, even in case of error. I didn't check if it's doable: maybe, in certain cases, we won't want to close the connection if an error occurs.

**Comment by sspans** [comment]
Yeah, I figured some of the recent changes would affect this.

We're hitting the leaks more often now with the older build we're running.
I'll do testing with a newer build and will send pull requests for any fixes needed.

**Comment by brmzkw** [comment]
Updating libgotftp with https://github.com/tftp-go-team/libgotftp/pull/6 should be enough :)

I'm on https://github.com/tftp-go-team/libgotftp/issues/7 now.

**Comment by brmzkw** [comment]
If there was an error (file not found, read or write error), `res.End()` wasn't called so the socket could not be free'd.

By merging https://github.com/tftp-go-team/libgotftp/issues/7 and this pull request, you will no longer have descriptor leaks.

**Comment by sspans** [comment]
Merged, I'll run tests next week.

Thanks!

**Comment by brmzkw** [comment]
wow, I don't know what was going on with me on Friday but I didn't created the pull request to fix the leak when a transfer fails. Instead, I pushed on the master branch of my fork.

Anyway, pull request done at https://github.com/tftp-go-team/hooktftp/pull/25
