### ISSUE TITLE
shell hook error code issue

### ISSUE THREAD

**Issue by lark** [tftp-go-team/hooktftp#27]
It's expected that shell hook script can exit with ENOENT or like, and tftp client can get error code and stop transfer immediately.

But if shell hook script exists and can be executed, the exit code is caught by deferred **cmd.Wait()**.  There is no chance that shell hook script returns error code to client. This makes shell hook less useful.

**Comment by rmedaer** [comment]
Could you send us a PR to fix it ?

Best regards,
