### ISSUE TITLE
More adstraction

### ISSUE THREAD

**Issue by bksworm** [tftp-go-team/hooktftp#3]
Hello, epeli!

I think you can add more functionality of your tool to make a possibility easily write hooks on Go itself.  

For ex. just by moving handleRRQ(), HOOKS[] and parts of the main function from line#145 dipper to the library. In such case any user will be able to create hooks ether by config file or by writing "dynamic" ones on Go.   

User case: To test some embedded card by I need to  upload ~2500 images by tftp resetting it every time and retrieve the same number of logs by  COM. Card downloads app.img file. Thus I need a way to fake it. Renaming files every time is not very good idea for me. 
Thanks for interesting project,
bks_worm

**Comment by brmzkw** [comment]
Couldn't you use a shell hook, and serve a different file depending on the client? The program executed gets the client's IP address through the environment variable CLIENT_ADDR (https://github.com/tftp-go-team/hooktftp/commit/11c6fa2d0e764659005845dc351ab2548873ba83)

**Comment by brmzkw** [comment]
Closing the issue. Feel free to reopen it if you think using a shell hook isn't enough.
